name: iKash CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # On se déplace dans Backend pour installer les dépendances
          pip install -r Backend/requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          # On vérifie uniquement le dossier Backend
          flake8 Backend/ --count --select=E9,F63,F7,F82 --show-source --statistics

  deploy:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        run: |
          curl -f ${{ secrets.RENDER_DEPLOY_HOOK }}